---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install apache2
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start apache2
    service:
      name: "{{mywebpackonubuntu}}"
      state: restarted 
    when: ansible_os_family =="Debian"